version: "3.9"

volumes:
  langgraph-data:
    driver: local

services:
  redis:
    image: docker.io/redis:6
    container_name: langgraph-redis
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 5

  postgres:
    image: docker.io/postgres:16
    container_name: langgraph-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - langgraph-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s

  api:
    # The 'image:' line was removed from here.
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: langgraph-api
    ports:
      - "8123:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      REDIS_URI: redis://redis:6379
      POSTGRES_URI: postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
    command: uvicorn app.server:app --host 0.0.0.0 --port 8000

  frontend:
    # The 'image:' line was removed from here.
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: langgraph-frontend
    ports:
      - "8124:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://api:8000

  migration:
    # The 'image:' line was removed from here.
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: langgraph-migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URI: postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
    command: alembic upgrade head
